name: Build and Deploy Go App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Go modules
      run: |
        if [ ! -f "go.mod" ]; then
          go mod init demo
          sed -i 's/^go .*/go 1.17/' go.mod
          go mod tidy
        fi

    - name: Build Docker image
      run: docker build -t go-demo .

    - name: Run Docker container
      run: |
        docker stop go-app || true
        docker rm go-app || true
        docker run -d -p 8888:8888 --name go-app go-demo
